---
title: "MUDAC 2019: Minnesota Water Quality"
author: "Genevieve Block, Ben Christensen, Sara Lawson, Delia Matos"
date: "April 23, 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(readxl)
require(knitr)
require(png)

```

## Outline


## Problem 1

- The question

- Data source

- Data size

- Goal: prediction v inference; regression v clsasification

## The Data

- types of variables

- ranges

- etc.

## Results

- Final model

- Interpretations

- Conclusions (what specific policy should Minnesota look at implementing?)


## Data Cleaning



## Data Exploration


## Cross-Validation


## Variable Selection


## Model Analysis

- What do the statistics and visualizations tell you about the strength, efficacy, accuracy of your model?


## Summary

 - Tell the story again
 
 

## Problem 2

- What is the effect of rainfall intensity on water quality?

        - Create Annual Precipitation Intensity Index
        - Measure correlation between index and TSS, Nitrate

- Minnesota Pollution Control Agency; Water Resource Center at Minnesota State University Mankato

- 2,875,000 rows of hourly precipitation data

        - 56 precipitation zones
        - 4 watersheds
        - 8 years

- Unsupervised; inference; regression (quantitative variables)


## The Data

- Location (data type)

- Timestamp (data type)

- Intensity (data type)

- Various year ranges 

        - 2007 - 2012
        - 2010 - 2014
        - 2009 - 2014


## Results

- Final model

- Interpretations

- Conclusions (what specific policy should Minnesota look at implementing?)


## Data Cleaning

- Convert to flat format in Excel

- Add columns 
        
        - rain/snow/spring (character)
        - Datetime (numeric)

- rbind to create one dataset


## Data Exploration

- intensity ranges

- outliers

- bins to view distribution of intensities 


## Variable Selection

- Heuristic from Problem Statement

- What information can we get out of the data? What variables can we create for the index?

- Which index variables contribute more?

- APII = .5 * (Hourly Rainfall Points) + .5 * (Maximum Points)


## Model Analysis

- We'll use lm(Index ~ TSS... to do this

        - for each watershed and over all years
        - Emphasize R^2

- Show graphs


## Summary

 - Tell the story again
 
 - Drive home how it ties into the overarching project
 


# MUDAC 2019: Minnesota Water Quality 